const FETCH_RATES_REQUEST = 'FETCH_RATES_REQUEST'
const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS'
const FETCH_RATES_FUILURE = 'FETCH_RATES_FUILURE'
const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY'

export {
  FETCH_RATES_REQUEST,
  FETCH_RATES_SUCCESS,
  FETCH_RATES_FUILURE,
  SET_BASE_CURRENCY,
}