const FETCH_RATES_REQUEST = 'FETCH_RATES_REQUEST'
const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS'
const FETCH_RATES_FUILURE = 'FETCH_RATES_FUILURE'
const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY'

const SET_EMPTY_STRING_ERROR = 'SET_EMPTY_STRING_ERROR'
const SET_INVALID_STRING_ERROR = 'SET_INVALID_STRING_ERROR'
const FETCH_PRICE_REQUEST = 'FETCH_PRICE_REQUEST'
const FETCH_PRICE_SUCCESS = 'FETCH_PRICE_SUCCESS'
const FETCH_PRICE_FUILURE = 'FETCH_PRICE_FUILURE'
const SET_STRING = 'SET_STRING'

export {
  FETCH_RATES_REQUEST,
  FETCH_RATES_SUCCESS,
  FETCH_RATES_FUILURE,
  SET_BASE_CURRENCY,
  SET_EMPTY_STRING_ERROR,
  SET_INVALID_STRING_ERROR,
  FETCH_PRICE_REQUEST,
  FETCH_PRICE_SUCCESS,
  FETCH_PRICE_FUILURE,
  SET_STRING
}